# Generated by Django 4.1.3 on 2023-08-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(blank=True, choices=[('estate_agent', 'Estate Agent'), ('papad_seller', 'Papad Seller'), ('maharaj_swami', 'Maharaj Swami'), ('lada_singer', 'Lada Singer'), ('rasoiyo', 'Rasoiyo'), ('maitinwaro', 'Maitinwaro'), ('maitinwari', 'Maitinwari'), ('doctor', 'Doctor'), ('engineer', 'Engineer'), ('genuine_properties', 'Genuine Properties'), ('safe_tourism', 'Safe Tourism'), ('social_workers', 'Social Workers'), ('education', 'Education'), ('food_industries', 'Food Industries'), ('advocates', 'Advocates'), ('entrepreneur', 'Entrepreneur'), ('EstateAgent', 'Estate Agent'), ('PapadSeller', 'Papad Seller'), ('Maharaj_Swami', 'Maharaj Swami'), ('LadaSinger', 'Lada Singer'), ('Rasoiyo', 'Rasoiyo'), ('Maitinwaro', 'Maitinwaro'), ('Maitinwari', 'Maitinwari'), ('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Genuine_Properties', 'Genuine Properties'), ('Safe_Tourism', 'Safe Tourism'), ('Social_Workers', 'Social Workers'), ('Education', 'Education'), ('Food_Industries', 'Food Industries'), ('Advocates', 'Advocates'), ('Entrepreneur', 'Entrepreneur')], max_length=50, null=True),
        ),
    ]
