# Generated by Django 4.1.3 on 2023-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_wellwisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellwisher',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wellwisher',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wellwisher',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wellwisher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
