# Generated by Django 4.1.3 on 2023-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_professional_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellwisher',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
